In [6]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

first_data = {
    "One" : [0, 2, 5, 6],
    "Two" : ["A", "B", "D", "C"]
}

second_data = {
    "One" : [0, 1, 5, 2],
    "Two" : ["B", "C", "E", "A"]
}

first = pd.DataFrame(first_data)
second = pd.DataFrame(second_data)

right = pd.merge(first, second, how='right', on='One')
left = pd.merge(first, second, how='inner', on='Two')



In [10]:
y = np.arange(12).reshape(4, 3)
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
y[(y > 5)] = -1
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [-1 -1 -1]
 [-1 -1 -1]]


In [16]:
x = np.array([[2, 4], [5, 1]])
z = np.ones_like(x)
print(z)

[[1 1]
 [1 1]]


In [29]:
w = np.eye(2) * x
print(w)

[[2. 0.]
 [0. 1.]]


In [27]:
x

array([[2, 4],
       [5, 1]])

In [37]:
import pandas as pd
import numpy as np

series1 = {
    "A" : 1, 
    "B" : 2, 
    "C" : 3, 
    "D" : 4 
}

series2 = {
    "A" : 5, 
    "B" : 6, 
    "D" : 7, 
    "E" : 8 
}

S1 = pd.Series(series1, name="S1")
S2 = pd.Series(series2, name="S2")

S2



A    5
B    6
D    7
E    8
Name: S2, dtype: int64

In [38]:
S1[:3] * 10

A    10
B    20
C    30
Name: S1, dtype: int64

In [39]:
S1 + S2

A     6.0
B     8.0
C     NaN
D    11.0
E     NaN
dtype: float64

In [42]:
S2[::-1] * 5

E    40
D    35
B    30
A    25
Name: S2, dtype: int64

#### 3 (a) Consider the following numpy array matrix:
#### [[5, 10, 20],[20, 13, 43],[34, 27, 67],[12, 46, 77]]
#### Give the output for following numpy commands:
#### (i) matrix.T
#### (ii) matrix [:1, 1:]

In [7]:
import numpy as np

matrix = [[5, 10, 20],[20, 13, 43],[34, 27, 67],[12, 46, 77]]
matrix = np.array(matrix)
matrix 

array([[ 5, 10, 20],
       [20, 13, 43],
       [34, 27, 67],
       [12, 46, 77]])

In [8]:
matrix.T

array([[ 5, 20, 34, 12],
       [10, 13, 27, 46],
       [20, 43, 67, 77]])

In [9]:
matrix[:1, 1:]  #array([[10, 20]])

array([[10, 20]])

In [11]:
matrix[[1, 3, 0], [2, 1, 0]] # array([43, 46, 5])

array([43, 46,  5])

In [12]:
matrix[[-2, -4]] # array([[34, 27, 67],[ 5, 10, 20]])

array([[34, 27, 67],
       [ 5, 10, 20]])

In [13]:
matrix[[True, False, False, True]]

array([[ 5, 10, 20],
       [12, 46, 77]])

In [14]:
matrix[3][:2] # array([12, 46])

array([12, 46])

In [15]:
matrix[::-1]

array([[12, 46, 77],
       [34, 27, 67],
       [20, 13, 43],
       [ 5, 10, 20]])

In [16]:
matrix.ndim

2

In [17]:
np.swapaxes(matrix, 1, 0)

array([[ 5, 20, 34, 12],
       [10, 13, 27, 46],
       [20, 43, 67, 77]])

In [18]:
matrix + 10

array([[15, 20, 30],
       [30, 23, 53],
       [44, 37, 77],
       [22, 56, 87]])

In [33]:
#4a
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataframe = {
    "One": [1, 34, np.nan, 34], 
    "Two" : [14, 21, 23, 21], 
    "Three" : [34,np.nan, np.nan, 32], 
    "Four" : [np.nan, 12, 2, 33], 
    "Five" : [np.nan, np.nan, np.nan, np.nan]
}

df = pd.DataFrame(dataframe)
df

One  Two  Three  Four  Five
0   1.0   14   34.0   NaN   NaN
1  34.0   21    NaN  12.0   NaN
2   NaN   23    NaN   2.0   NaN
3  34.0   21   32.0  33.0   NaN

In [44]:
df[['One', 'Two', 'Three', 'Four', 'Five']].dropna()

C:\Users\Ganesh\AppData\Local\Temp\ipykernel_8920\919607514.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['One', 'Three', 'Four', 'Five']].dropna(inplace=True)


In [47]:
mean = df["One"].mean()
df["One"].fillna(mean, inplace=True)
df

C:\Users\Ganesh\AppData\Local\Temp\ipykernel_8920\3312485998.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["One"].fillna(mean, inplace=True)


One  Two  Three  Four  Five
0   1.0   14   34.0   NaN   NaN
1  34.0   21    NaN  12.0   NaN
2  23.0   23    NaN   2.0   NaN
3  34.0   21   32.0  33.0   NaN

In [48]:
mat = np.array([[[-1, 2],[3, 4]], [[-5, 6], [7, 8]]])
mat

array([[[-1,  2],
        [ 3,  4]],

       [[-5,  6],
        [ 7,  8]]])

In [49]:
arr1 = np.zeros_like(mat)
arr1

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [50]:
mat.shape

(2, 2, 2)

In [51]:
mat.dtype

dtype('int64')

In [52]:
mat[mat > 6]

array([7, 8])

In [57]:
mat_float = mat.astype(np.float64)  # astype makes new copy of the ndarray
mat_float.dtype

dtype('float64')

In [58]:
mat * 25

array([[[ -25,   50],
        [  75,  100]],

       [[-125,  150],
        [ 175,  200]]])

In [61]:
#5a 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dict_data = {
    "Key" : ["A", "B", "C", "D", "E"], 
    "Value" : ["List of numbers from 1 to 10 skipping 2 at a time", 
              "List of Strings from A to E", 
              "List of 5 numbers obtained using random normal distribution function", 
              "List of  random integers from 20 to 30", 
              "Square root of 5 random numbers from 50 to 70"]
}

df = pd.DataFrame(dict_data)
df


Key                                              Value
0   A  List of numbers from 1 to 10 skipping 2 at a time
1   B                        List of Strings from A to E
2   C  List of 5 numbers obtained using random normal...
3   D             List of  random integers from 20 to 30
4   E      Square root of 5 random numbers from 50 to 70

In [63]:
# index = ["A", "B", "C","D", "E"]
index = df["Key"]
df = pd.DataFrame(dict_data , index=index)
df

Key                                              Value
Key                                                       
A     A  List of numbers from 1 to 10 skipping 2 at a time
B     B                        List of Strings from A to E
C     C  List of 5 numbers obtained using random normal...
D     D             List of  random integers from 20 to 30
E     E      Square root of 5 random numbers from 50 to 70