In [6]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

first_data = {
    "One" : [0, 2, 5, 6],
    "Two" : ["A", "B", "D", "C"]
}

second_data = {
    "One" : [0, 1, 5, 2],
    "Two" : ["B", "C", "E", "A"]
}

first = pd.DataFrame(first_data)
second = pd.DataFrame(second_data)

right = pd.merge(first, second, how='right', on='One')
left = pd.merge(first, second, how='inner', on='Two')



In [10]:
y = np.arange(12).reshape(4, 3)
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
y[(y > 5)] = -1
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [-1 -1 -1]
 [-1 -1 -1]]


In [16]:
x = np.array([[2, 4], [5, 1]])
z = np.ones_like(x)
print(z)

[[1 1]
 [1 1]]


In [29]:
w = np.eye(2) * x
print(w)

[[2. 0.]
 [0. 1.]]


In [27]:
x

array([[2, 4],
       [5, 1]])

In [37]:
import pandas as pd
import numpy as np

series1 = {
    "A" : 1, 
    "B" : 2, 
    "C" : 3, 
    "D" : 4 
}

series2 = {
    "A" : 5, 
    "B" : 6, 
    "D" : 7, 
    "E" : 8 
}

S1 = pd.Series(series1, name="S1")
S2 = pd.Series(series2, name="S2")

S2



A    5
B    6
D    7
E    8
Name: S2, dtype: int64

In [38]:
S1[:3] * 10

A    10
B    20
C    30
Name: S1, dtype: int64

In [39]:
S1 + S2

A     6.0
B     8.0
C     NaN
D    11.0
E     NaN
dtype: float64

In [42]:
S2[::-1] * 5

E    40
D    35
B    30
A    25
Name: S2, dtype: int64